name: CNN

path: ../models

model:
  sequence_length: 56
  num_classes: 2
  vocab_size: 18758
  embedding_size: 128
  filter_sizes:
    - 2
    - 3
    - 4
    - 5
  num_filters: 2
  learning_rate: 0.003

train:
  batch_size: 64
  epoch: 20
